name: 'Kith & Kine'
favicon: null
layout_spectrum: 0.047087669372558594
typography_spectrum: 0.35259770322591066
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7958877882920206
  lightness: 0.27163040777668357
  saturation: 0.565314298029989
  rhythmicContrast: 0.9418284532148391
purpose: []
